# Generated by Django 4.2.7 on 2023-12-11 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_car_customuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.DateField()),
                ('data', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('presenca', models.CharField(max_length=255)),
                ('comentarios', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Usuario',
        ),
        migrations.AddField(
            model_name='eventos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.usuario'),
        ),
    ]
