# Generated by Django 4.2.7 on 2023-12-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_eventos_delete_car_rename_customuser_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=255)),
                ('presenca', models.CharField(max_length=255)),
                ('comentarios', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.AddField(
            model_name='events',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.users'),
        ),
    ]
