# Generated by Django 4.2.7 on 2023-12-12 23:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_events_rename_usuario_users_delete_eventos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='UserRegister',
        ),
    ]
