# Generated by Django 4.2.7 on 2024-01-09 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_rename_events_event_rename_users_userregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventModel',
        ),
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='UserModel',
        ),
    ]
