# Generated by Django 4.2.7 on 2024-01-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_event_eventmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='usuario',
            new_name='user_id',
        ),
    ]
